package org.alexdev.kepler.game.item.base;

public enum ItemBehaviour {
    SOLID,
    CAN_STACK_ON_TOP,
    CAN_SIT_ON_TOP,
    CAN_STAND_ON_TOP,
    CAN_LAY_ON_TOP,
    CUSTOM_DATA_NUMERIC_ON_OFF,
    REQUIRES_TOUCHING_FOR_INTERACTION,
    CUSTOM_DATA_TRUE_FALSE,
    PUBLIC_SPACE_OBJECT,
    EXTRA_PARAMETER,
    DICE,
    CUSTOM_DATA_ON_OFF,
    CUSTOM_DATA_NUMERIC_STATE,
    TELEPORTER,
    REQUIRES_RIGHTS_FOR_INTERACTION,
    GATE,
    PRIZE_TROPHY,
    ROLLER,
    REDEEMABLE,
    SOUND_MACHINE,
    SOUND_MACHINE_SAMPLE_SET,
    JUKEBOX,
    WALL_ITEM,
    POST_IT,
    DECORATION,
    WHEEL_OF_FORTUNE,
    ROOMDIMMER,
    PRESENT,
    PHOTO,
    PLACE_ROLLER_ON_TOP,
    INVISIBLE,
    EFFECT,
    ELEVATION,

    REDIRECT_ROTATION_0,
    REDIRECT_ROTATION_2,

    SONG_DISK, REDIRECT_ROTATION_4,

    PET_WATER_BOWL,

    PET_FOOD,
    PET_CAT_FOOD,
    PET_DOG_FOOD,
    PET_CROC_FOOD,

    PRIVATE_FURNITURE;
}
