package net.h4bbo.http.kepler.util;

import java.util.Arrays;
import java.util.List;
import java.util.concurrent.ThreadLocalRandom;

public class TagUtil {
    public static String getRandomQuestion() {
        var questions = getRandomQuestions();

        String question = questions.get(ThreadLocalRandom.current().nextInt(0, questions.size()));
        //question = question.toLowerCase();
        //question = question.substring(0, 1).toUpperCase() + question.substring(1);

        return question;

    }
    public static List<String> getRandomQuestions() {
        var stringList = new String[] {
                "Dog or Cat?",
                "Netflix or YouTube?",
                "Phone Call or Text?",
                "Toast or Eggs?",
                "Cardio or Weights?",
                "Facebook or Twitter?",
                "Ice Cream Cone or Snow Cone?",
                "Mobile Games or Console Games?",
                "Music or Podcasts?",
                "iOS or Android?",
                "Form or Function?",
                "Pop or Indie?",
                "Cake or Pie?",
                "Swimming or Sunbathing?",
                "High-tech or Low-tech?",
                "Big Party or Small Gathering?",
                "New Clothes or New Phone?",
                "Rich Friend or Loyal Friend?",
                "Football or Basketball?",
                "Work Hard or Play Hard?",
                "Nice Car or Nice Home Interior?",
                "What’s worse: Laundry or Dishes?",
                "Jogging or Hiking?",
                "Bath or Shower?",
                "Sneakers or Sandals?",
                "Glasses or Contacts?",
                "Hamburger or Taco?",
                "Couch or Recliner?",
                "Online Shopping or Shopping in a Store?",
                "Receive: Email or Letter?",
                "Passenger or Driver?",
                "Tablet or Computer?",
                "Intelligent or Funny?",
                "Car or Truck?",
                "Blue or Red?",
                "Money or Free Time?",
                "Amusement Park or Day at the Beach?",
                "At a movie: Candy or Popcorn?",
                "Pen or Pencil?",
                "Toilet paper: Over or Under?",
                "Cups in the cupboard: Right Side Up or Up Side Down?",
                "Pancake or Waffle?",
                "Coke or Pepsi?",
                "Coffee Cup or Thermos?",
                "Blinds or Curtain?",
                "Train or Plane?",
                "Phone or Phablet?",
                "Iced Coffee or Hot Coffee?",
                "Meat or Vegetables?",
                "International Vacation or a New TV?",
                "Save or Spend?",
                "Honesty or Other’s Feelings?",
                "Coffee or Tea?",
                "TV or Book?",
                "Movie at Home or Movie at the Theater?",
                "Ocean or Mountains?",
                "Horror Movie or Comedy Movie?",
                "City or Countryside?",
                "Winter or Summer?",
                "Mac or PC?",
                "Console Gaming or PC Gaming?",
                "Soup or Sandwich?",
                "Card Game or Board Game?",
                "Classical Art or Modern Art?",
                "Beer or Wine?",
                "Dine In or Delivery?",
                "Sweater or Hoodie?",
                "Comic Book or Comic Strips?",
                "Motorcycle or Bicycle?",
                "Book or eBook?",
                "Ninjas or Pirates?",
                "TV Shows or Movies?",
                "Fish or steak?",
                "Eggs or oatmeal?",
                "Coffee or tea?",
                "Coke or Pepsi?",
                "Beer or mixed drinks?",
                "Juice or water?",
                "White or wheat bread?",
                "Cake or donuts?",
                "Vanilla or chocolate?",
                "Ice cream or sherbet?",
                "Pork or chicken?",
                "Bacon or sausage?",
                "Scrambled eggs or over easy?",
                "Over easy or poached eggs?",
                "Cream and sugar or black coffee?",
                "Well done or rare?",
                "Corn or peas?",
                "Salad or squash?",
                "Green beans or broccoli?",
                "Black beans or kidney beans?",
                "Pinto or Lima beans?",
                "Frozen veggies or canned?",
                "Pancakes or waffles?",
                "Pastries or confectionaries?",
                "Burgers or seafood?",
                "Food truck or diner?",
                "Ginger ale or Sprite?",
                "Orange soda or Grape?",
                "Trail mix or candy bar?",
                "Payday or 5th avenue?",
                "Reese’s peanut butter cup or Hershey’s bar?",
                "Almond Joy or Snickers?",
                "Three Musketeers or Peppermint Patty?",
                "O’Henry or Baby Ruth?",
                "Apples or bananas?",
                "Oranges or peaches?",
                "Watermelon or plums?",
                "Cantaloupe or grapefruit?",
                "Cake or pie?",
                "Pastries or cookies?",
                "Hash browns or home fries?",
                "Jello or pudding?",
                "Cherry or raspberry?",
                "Grape or orange?",
                "Lime or blueberry?",
                "Slim Jim or Jerky?",
                "Cupcake or Dingdong?",
                "Swiss cake or Hoho?",
                "Gum or Lifesavers?",
                "Tic-tac or Altoids?",
                "Tootsie rolls or Skittles?",
                "Licorice or fruit roll ups?",
                "Popcorn or peanuts?",
                "Hot pretzels or nachos?",
                "Grilled or pan fried?",
                "Deep fried or baked?",
                "Apple or cherry pie?",
                "Sugar or chocolate chip cookies?",
                "Pumpkin or blueberry?",
                "Pie or cobbler?",
                "Breaded or plain?",
                "Iced or hot coffee?",
                "Hot or iced tea?",
                "Sweetened tea or unsweetened?",
                "Chinese or Italian?",
                "Indian or Thai?",
                "American or Mexican?",
                "Sweet or sour?",
                "Eat in or dine out?",
                "Cook at home or take out?",
                "Cheeseburger or calamari?",
                "Hot dog or taco?",
                "Stew or chili?",
                "Sweet potato or French fries?",
                "Baked potato or onion rings?",
                "Ketchup or mustard?",
                "Mayo or salad dressing?",
                "Sandwich or soup?",
                "Ribs or wings?",
                "Family run or chain restaurant?",
                "Cook out in backyard or catered?",
                "Wine or beer?",
                "Jack Daniels or Jim Beam?",
                "Irish coffee or plain coffee?",
                "Orange juice or grapefruit juice?",
                "Re-fried beans or rice?",
                "Tacos or chicken parmigiana?",
                "Pizza or subs?",
                "Peanuts or almonds?",
                "Cashews or hazelnut?",
                "Walnuts or sunflower seeds?",
                "Garlic or onion?",
                "Bagels or English muffins",
                "Poppy seed or onion rolls?",
                "Cinnamon or blueberry bagels?",
                "Everything or sesame seed bagels?",
                "Thousand Island or Ranch?",
                "Catalina or vinaigrette?",
                "Onion dip or bacon horseradish dip?",
                "Cheese fries or chili fries?",
                "French fries or onion rings?",
                "Cheese and crackers or pretzels?",
                "Chips with dip or vegetables and dip?",
                "Fruit or vegetables?",
                "Dinner rolls or croissant rolls?",
                "Biscuits or bread?",
                "Whole wheat or rye?",
                "Whole grain or white?",
                "Corn muffin or blueberry?",
                "Pastrami or bologna?",
                "Italian sub or ham and cheese?",
                "Turkey and cheese or roast beef sub?",
                "Sub roll or ciabatta roll?",
                "Sour cream and onion chips or barbecue?",
                "Cheddar and sour cream or salt and vinegar?",
                "Corn chips or Doritos?",
                "Action movies or dramas?",
                "Comedy or thrillers?",
                "Romantic or documentaries?",
                "Reality or fiction?",
                "Family or adult movies?",
                "Netflix or Hulu?",
                "Cable or satellite?",
                "Watch live or recorded so you don’t have to watch commercials?",
                "Television or book?",
                "Detective novels or super heroes?",
                "Romance novels or spy novels?",
                "Horror stories or mysteries?",
                "Rock or country?",
                "Pop or reggae?",
                "Choose classical or rap?",
                "Smooth jazz or techno?",
                "Standards or classic country like Johnny Cash?",
                "Bound book or Ebook?",
                "Newspaper or online news blog?",
                "Play or musical?",
                "Dancing or cooking classes?",
                "Concert or play?",
                "Massage or facial?",
                "Bowling or theater?",
                "Paint ball or arcade?",
                "Crocheting or knitting?",
                "Cards or board games?",
                "Carnival or circus?",
                "Roller coasters or ferris wheel?",
                "Woodworking or leather working?",
                "Darts or pool?",
                "Gardening or walking?",
                "Jeans and tee or a suit?",
                "Dress or pants?",
                "Formal or casual?",
                "Sneakers or dress shoes?",
                "Sandals or high heels?",
                "Make up or none?",
                "Black and white décor?",
                "Elegant or casual interior?",
                "Eclectic or organized interior?",
                "Leather or fabric?",
                "Sneakers or sandals?",
                "Flip flops or water shoes?",
                "Paintings or photos?",
                "Black and white or color?",
                "Drapes or blinds?",
                "Plants or collectibles?",
                "Chandelier or lamps?",
                "Paper or paneling?",
                "Paint or paper?",
                "Rugs or hardwood floors?",
                "Modern or rustic?",
                "Retro or antique?",
                "Ranch style or two-story home?",
                "Farmhouse kitchen or galley style?",
                "Car or truck?",
                "European or lake front style home?",
                "Riding mower or push?",
                "Apartment or home?",
                "Work boots or cowboy boots?",
                "Country or city?",
                "Rural or suburban?",
                "Farm or just an acre or two?",
                "Neutral colors or bold?",
                "Stoneware or China?",
                "Colonial or cottage style home?",
                "Candles or wax melts?",
                "Fireplace or furnace?",
                "Wicker or wood?",
                "Metal or wood?",
                "Wood or gas for a cook stove?",
                "Butcher block or granite counter-tops?",
                "Stainless steel or Teflon cookware?",
                "Skylights or mirrored wall?",
                "Spiral or straight stairs?",
                "Shag or tight pile?",
                "Leather or fabric?",
                "Wood or metal and glasses?",
                "Hardwood chairs or padded?",
                "Houseboat or yacht?",
                "Landscaped yard or just lawn?",
                "Game room or sewing room?",
                "Farmhouse or shingle style home?",
                "Stainless steel or porcelain sink?",
                "Wood cabinets or metal in kitchen?",
                "Log cabin or contemporary style home?",
                "Sun porch or deck?",
                "Manicure or make over?",
                "Football or baseball?",
                "Soccer or hockey?",
                "Golf or basketball?",
                "Racing or polo?",
                "Soccer or football?",
                "Field hockey or ice hockey?",
                "Polo or horse racing?",
                "Nascar or drag racing?",
                "College or pro?",
                "Touch or tackle football when you play?",
                "Short stop or third base?",
                "First base or outfielder?",
                "Catcher or pitcher?",
                "Winger or defenseman?",
                "Goalie or defenseman?",
                "Hunting or fishing?",
                "Deer or bear?",
                "Elk or moose?",
                "Bass or tuna?",
                "Ocean or lake?",
                "Lake or river?",
                "Skiing or surfing?",
                "Xbox or PS?",
                "Multiplayer or single player?",
                "Sports or shooter?",
                "Strategy or puzzle?",
                "Pacman or Tetris?",
                "Foosball or Ping-Pong?",
                "Computer or game consoles?",
                "Fantasy leagues or playing with your buds?",
                "Live action role playing or online gaming?",
                "Wrestling or mix martial arts?",
                "Bowling or tennis?",
                "Poker or chess?",
                "Volley ball or skateboarding?",
                "Cardio or weightlifting?",
                "Go to gym or home exercise?",
                "Boats or 4 wheelers?",
                "Walking or jogging?",
                "Weightlifting or pilates?",
                "Off road or race track?",
                "Skiing or snowboarding?",
                "Sweating to the oldies or playing handball?",
                "Working out three times a week or every day?",
                "Eating whatever you want or eating healthy to stay in shape?",
                "Workout alone or with a partner?",
                "Swimming or reading?",
                "Paintball or motocross?",
                "BMX racing or hang-gliding?",
                "Skateboarding or swimming?",
                "Triathlon or marathon running?",
                "Personal trainer or work out alone?",
                "Nutritionist or make your own meal plan?",
                "Skeet shoot or archery?",
                "TRAVEL",
                "Domestic or international?",
                "Drive or fly?",
                "Plane or boat?",
                "Amusement park or historical sites?",
                "Train or bus?",
                "Hunting trip or ski resort?",
                "Tropical or artic?",
                "Hot tub or hot springs?",
                "Spring or fall?",
                "Winter or summer?",
                "Auctions or closeout sales?",
                "Performing arts or science?",
                "Grand Canyon or Jelly Stone?",
                "Marlin fishing or wild boar hunting?",
                "Ghost tour or historical tour?",
                "Art festival or music festival?",
                "Renaissance fair or craft fair?",
                "Flea market or mall?",
                "Carnival or theme park?",
                "Zoo or aquarium?",
                "Thunderstorm or snow storm?",
                "State parks or off the beaten path?",
                "Interstates or back roads?",
                "Truck or motorcycle?",
                "Beach or mountain climbing?",
                "Architectural sites or shopping?",
                "Hiking or monster truck rally?",
                "Spa or gym?",
                "Nature or indoors?",
                "Tent or RV?",
                "Ghost hunting or artifact hunting",
                "A cruise or romantic retreat package?",
                "Ireland or Hong Kong?",
                "Anthropology dig or safari?",
                "Jamaica or Rio?",
                "Africa or Asia?",
                "Mexico or Monte Carlo?",
                "New York City or Vegas?",
                "LA or Atlanta?",
                "Phoenix or St. Louis?",
                "Portland or Seattle?",
                "Boston or Miami?",
                "Time share or motel?",
                "Rental home or bed and breakfast?",
                "Antiquing or Flea markets?",
                "Museums or observatory?",
                "Group travel or alone?",
                "Fireman or policeman?",
                "Doctor or nurse?",
                "Military or civilian?",
                "Boss or worker?",
                "Lawyer or carpenter?",
                "Plumber or stock market?",
                "Taxi driver or bus driver?",
                "Railroad engineer or mechanical Engineer?",
                "Wood working or automotive mechanic?",
                "Supervisor or hourly employee?",
                "Self-employed or a company man?",
                "Office work or outside work?",
                "Work from home or commute to work?",
                "Pilot or ship captain?",
                "Electrician or engineer?",
                "Author or editor?",
                "A job you love or one that pays you more money?",
                "Fisherman or lumberjack?",
                "Farmer or factory worker?",
                "Gas station attendant or sales clerk?",
                "Government work or private sector?",
                "Work on a team or to work alone?",
                "Landscaper or welder?",
                "Fashion designer or interior designer?",
                "Meetings all day or producing goods?",
                "Working with your hands or with a computer?",
                "Working in a store with the public or working in research?",
                "A long commute or a short commute to work?",
                "Party planner or printer?",
                "Anthropologist or astronomer?",
                "Suit and tie or jeans?",
                "Coveralls or scrubs?",
                "Drug representative or researcher?",
                "Cook or waitress?",
                "Janitor or IT tech?",
                "Banker or stock trader?",
                "Insurance actuary or detective?",
                "Street sweeper or sanitation supervisor?",
                "Telemarketer or appointment setter?",
                "Secretary or office manager?",
                "Physical therapist or psychologist?",
                "Rock star or race car driver?",
                "Country singer or professional athlete?",
                "Wrestler or football player?",
                "Professional bowler or poker player?",
                "Professional league coach or college coach?",
                "Professional cheerleader or model?",
                "Actor or model?",
                "Actress or talk show host?",
                "News anchor or meteorologist?",
                "Construction worker or artist?",
                "Newspaper editor or reporter?",
                "Journalist or photographer?",
                "Dentist or podiatrist?",
                "Medical examiner or emergency doctor?",
                "Teacher or administrator?",
                "Auctioneer or sports caster?",
                "Stock broker or day trader?",
                "Author or advertising agent?",
                "Truck mechanic or long haul driver?",
                "Salesman or lawyer?",
                "Artist or curator?",
                "Shower or bath?",
                "Dog or cat?",
                "Tattoo or piercings?",
                "Smoke or chew?",
                "Sleep in PJs or nude?",
                "Silk or flannel sheets?",
                "Egyptian cotton or silk?",
                "Regular bed or waterbed?",
                "Savings or shopping?",
                "Night owl or early riser?",
                "A slacker or an overachiever?",
                "3 meals a day or 5 small meals?",
                "Silver or gold?",
                "Pen or pencil?",
                "Green or blue eyes?",
                "Contacts or glasses?",
                "Adventurous or cautious?",
                "Call or text?",
                "Email or snail mail?",
                "Long or short hair?",
                "Freckles or dimples?",
                "Shy or outgoing?",
                "Automated answering service or speak to a live person?",
                "Frozen pizza or Dominoes?",
                "Pizza hut or Little Caesars?",
                "Sweater or hoodie?",
                "When hanging toilet paper, over or under?",
                "Blue or red?",
                "Green or white?",
                "Pants or shorts?",
                "Brains or beauty?",
                "Date someone older or younger than yourself?",
                "Beads or pearls?",
                "Mac or PC?",
                "Take time to style your hair or wear a cap?",
                "Dye your hair or have natural color?",
                "Natural or breast implants?",
                "Give roses or daisies?",
                "Receive roses or daisies?",
                "For a snack something salty or sweet?",
                "Facebook or twitter?",
                "Charmin or Angel Soft?",
                "Scrubbing bubbles or Lysol?",
                "Flower or vegetable garden?",
                "High tech or low tech?",
                "Security system or a dog?",
                "A large crowd or a small party?",
                "Telepathy or teleporting?",
                "Hero or villain?",
                "Dominate or subservient?",
                "Money or fame?",
                "Encounter ghost or demons?",
                "Vampires or angels?",
                "A witch or sorcerer?",
                "Pirates or a motorcycle gang?",
                "Quick temper or to have control?",
                "Kisses or hugs?",
                "Sugar or spice?",
                "After shave or cologne?",
                "Perfume or body spray?",
                "Healthy or comfort food?",
                "Necklace or Bracelet?",
                "Cubed or crushed ice?",
                "Swimming or sunbathing?",
                "Sofa or recliner?",
                "Candle light or lamp light?",
                "Online or in store shopping?",
                "Good Will or Macy’s?",
                "Pudding or custard?",
                "Google or Bing?",
                "Roommate a neat freak or a messy person?",
                "Movies at home or in theaters?",
                "Your nails, long or short?",
                "Home garden or go to farmers market?",
                "Your day – crazy or sane?",
                "Live in the past or present?",
                "Paper or plastic bags?",
                "Open spaces or small closed in areas?",
                "For dinning, paper plates or china?",
                "Watch sports or play?",
                "Kids or pets?",
                "Spend time in living room or bedroom?",
                "Cremation or burial?",
                "Life support to keep you alive for years or not?",
                "A maid or a cook?",
                "Live in a cold or hot area?",
                "For home pets, hamster or rabbit?",
                "Pet fish or a lizard?",
                "Christmas or Halloween?",
                "Thanksgiving or Easter?",
                "Memorial Day or St. Patrick’s Day?",
                "New Year’s or Valentines?",
                "American made or imports?",
                "Slippers or barefoot?",
                "Public library or bookstore?",
                "Dunkin Donuts or Tim Horton?",
                "Starbucks or Dunkin Donuts?",
                "Whole bean or ground?",
                "Loose leaf or teabag?",
                "Glazed donut or jelly?",
                "Cinnamon bun or danish?",
                "Pictionary or charades?",
                "A rainy Sunday in bed or the mall?",
                "Prepaid or contract cell plan?",
                "College or trade school?",
                "Public education or home school?",
                "Straw hat or baseball cap?",
                "Cowboy hat or knit cap?",
                "Sunglasses or sun visor?",
                "Elegant or casual dinner?",
                "E-harmony or Match?",
                "Plenty of Fish or Zoosk?",
                "Many causal friends or just a few close friends?",
                "Surprise party or theme party?",
                "Costume party or pool party?",
                "Luau or pig roast?",
                "Cell phone or landline?",
                "Home owner or renter?",
                "Bubble bath or just a hot soak?",
                "Eye sight or hearing?",
                "Taste or smell?",
                "Be creative or genius?",
                "Lounge wear or jeans?",
                "Swimming pool or lake?",
                "Strategy games or Bingo?"
        };

        return Arrays.asList(stringList);
    }
}
